application: gae2048
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app
  
- url: /static
  static_dir: static

- url: /static/images
  static_dir: static/images
  
- url: /static/css
  static_dir: static/css
    
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  

libraries:
- name: jinja2
  version: latest
  
builtins:
- remote_api: on